### PR TITLE
Feature/add new pages

### PR DESCRIPTION
**Pull request by Tejas-Thind**
Created all the required pages we are gonna need. Also testing out the workflow, and if it works properly.

### CODE REVIEW

**Comment by Gateek-Chandak** [comment]
I do not approve of the secret message

**Review by Gateek-Chandak — APPROVED** [review]
everything looks good.

**Review by jinayang15 — APPROVED** [review]
looks good to me

**Review by pratham-s2 — APPROVED** [review]
looks good

**Pull request merged**
